### ISSUE TITLE
Request feature: Ability to specify interval bars other than time

### ISSUE THREAD

**Issue by sunsetcoder** [nhedlund/qdownload#2]
Would really appreciate it if you could include the feature to specify the interval type, to download interval bars (eg. new bar every 100 shares traded).

eg. qdownload -v 100 aapl
would download a csv with a new OHLC row after every 100 shares traded

[IntervalType] - Optional - 's' (default) for time intervals in seconds, 'v' for volume intervals, 't' for tick intervals

 It's already implemented in the IQFeed developer API for historical data.

**Comment by nhedlund** [comment]
I agree, interval bars would be good to include. Will look into it when time permits.

**Comment by nhedlund** [comment]
Interval bars is now supported for volume, ticks and seconds.

I also added support for end of bar timestamps that some trading software use, but this is an option. Start of bar timestamps is still default.

**Comment by sunsetcoder** [comment]
Thank you!! I hope to assist with features in future once I have learnt Golang.
