### ISSUE TITLE
Compile issues due to changes in urfave/cli

### ISSUE THREAD

**Issue by wiretail** [nhedlund/qdownload#3]
Currently building will fail with >v1 of urfave/cli.  Quick fix is changing the import to "gopkg.in/urfave/cli.v1" without any other code changes.

But didn't want to send that in a pull in case you'd prefer to update the script instead. (I'm not a Go programmer for the most part...and I failed at a stab in updating it the v2/3.)

**Comment by nhedlund** [comment]
Thanks for the quick fix, going with that for now.
